# CreditPilot — Feature Engineering & Data Preprocessing

## Overview
This notebook focuses on transforming raw financial data into a format suitable for machine learning. It involves feature engineering, encoding categorical variables, scaling numerical features, and preparing the dataset for model training.

---

## Objectives

- Create meaningful derived features  
- Encode categorical variables  
- Normalize / scale numerical features  
- Prepare clean dataset for ML models  
- Separate features (X) and target (y)  

---


## Key Steps

### 1. Feature Engineering
- Create new ratios and transformations  
- Improve predictive power  

### 2. Encoding
- Convert categorical variables into numerical format  

### 3. Scaling
- Normalize numerical features for better ML performance  

### 4. Final Dataset Preparation
- Split features and target  
- Save processed dataset  

---

## Next Step

 Model Training & Evaluation

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [3]:
df = pd.read_csv("../data/raw/creditpilot_dataset.csv")
df.head()

,user_id,age,employment_type,employment_length_years,annual_income,income_stability_score,loan_amount,loan_term_months,interest_rate,loan_type,...,emi_to_income_ratio,loan_to_income_ratio,num_credit_inquiries,late_payment_count,default_history,repayment_history_score,credit_history_length_years,job_stability_score,spending_to_income_ratio,loan_status
0,1,59,salaried,18,200000.000000,85.0,175387.433746,60,8.198239,education,...,0.214373,0.876937,3,0,0,82.310176,22,90.0,0.675222,0
1,2,49,self-employed,3,289124.248220,27.5,194435.024170,48,9.811462,personal,...,0.203945,0.672496,2,3,0,38.582487,4,15.0,0.290793,0
2,3,35,salaried,3,200000.000000,47.5,122620.314192,36,9.658658,education,...,0.236219,0.613102,6,6,1,24.476369,3,15.0,0.635074,1
3,4,28,unemployed,0,200000.000000,20.0,249992.823707,36,11.239523,auto,...,0.492770,1.249964,1,0,0,89.003286,1,10.0,0.472154,1
4,5,41,salaried,2,253596.809558,45.0,309077.838184,60,12.904879,auto,...,0.332059,1.218777,1,0,0,74.314983,4,10.0,0.664146,1

## Recalculate (ensuring consistency)

In [4]:

df["emi_to_income_ratio"] = df["emi"] / (df["annual_income"] / 12)
df["loan_to_income_ratio"] = df["loan_amount"] / df["annual_income"]
df["debt_to_income_ratio"] = df["total_debt"] / df["annual_income"]

# Risk-related engineered feature
df["credit_risk_score"] = (
    (850 - df["credit_score"]) * 0.4 +
    df["debt_to_income_ratio"] * 100 * 0.3 +
    df["credit_utilization_ratio"] * 100 * 0.3
)

## Encoding Categorical Variables

In [5]:
le = LabelEncoder()

df["employment_type"] = le.fit_transform(df["employment_type"])
df["loan_type"] = le.fit_transform(df["loan_type"])

## Feature Selection

In [6]:
df = df.drop(columns=["user_id"])

## Split Features & Target

In [7]:
X = df.drop("loan_status", axis=1)
y = df["loan_status"]

## Scaling

In [8]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

## Final Dataset

In [9]:
final_df = X_scaled.copy()
final_df["loan_status"] = y.values

final_df.head()

,age,employment_type,employment_length_years,annual_income,income_stability_score,loan_amount,loan_term_months,interest_rate,loan_type,emi,...,loan_to_income_ratio,num_credit_inquiries,late_payment_count,default_history,repayment_history_score,credit_history_length_years,job_stability_score,spending_to_income_ratio,credit_risk_score,loan_status
0,1.694087,-0.739074,1.541577,-0.450828,1.607075,-0.365883,-0.195427,-1.512826,-0.689882,-0.582169,...,-0.300782,-0.020060,-1.247497,-0.263013,0.814276,1.829270,1.598032,1.168108,-0.920944,0
1,0.799515,0.757027,-0.915354,0.210809,-1.331979,-0.324136,-0.355534,-0.457832,1.023259,-0.352031,...,-0.443067,-0.594841,1.215803,-0.263013,-2.207862,-1.064407,-1.038085,-1.416210,-0.761487,0
2,-0.452886,-0.739074,-0.915354,-0.450828,-0.309700,-0.481535,-0.515642,-0.557760,-0.689882,-0.519678,...,-0.484404,1.704283,3.679103,3.802098,-3.182774,-1.225166,-1.038085,0.898211,-0.763171,1
3,-1.079087,2.253128,-1.406741,-0.450828,-1.715334,-0.202368,-0.515642,0.476072,-1.546452,0.214183,...,-0.041167,-1.169621,-1.247497,-0.263013,1.276855,-1.546686,-1.213826,-0.197016,-0.399412,1
4,0.083857,-0.739074,-1.079150,-0.052938,-0.437485,-0.072868,-0.195427,1.565160,-1.546452,0.009017,...,-0.062873,-1.169621,-1.247497,-0.263013,0.261707,-1.064407,-1.213826,1.093646,0.866214,1

## Save Processed Data

In [10]:
final_df.to_csv("../data/processed/final_dataset.csv", index=False)

## Quick Check

In [11]:
final_df.describe()

,age,employment_type,employment_length_years,annual_income,income_stability_score,loan_amount,loan_term_months,interest_rate,loan_type,emi,...,loan_to_income_ratio,num_credit_inquiries,late_payment_count,default_history,repayment_history_score,credit_history_length_years,job_stability_score,spending_to_income_ratio,credit_risk_score,loan_status
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,...,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000
mean,-3.019807e-16,-2.131628e-18,-1.278977e-17,1.222134e-16,1.357137e-16,3.410605e-17,3.979039e-17,5.172751e-16,1.087130e-16,9.219292e-17,...,-1.136868e-17,4.831691e-17,-3.410605e-17,5.044853e-17,-2.003731e-16,-4.902745e-17,-1.136868e-17,-2.188472e-16,-3.325340e-16,0.574900
std,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,...,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,0.494383
min,-1.705287e+00,-7.390739e-01,-1.406741e+00,-4.508282e-01,-1.715334e+00,-6.623477e-01,-8.358564e-01,-1.642126e+00,-1.546452e+00,-1.032638e+00,...,-7.718908e-01,-1.744402e+00,-1.247497e+00,-2.630127e-01,-3.492147e+00,-1.546686e+00,-1.213826e+00,-2.698813e+00,-1.964160e+00,0.000000
25%,-8.107150e-01,-7.390739e-01,-9.153543e-01,-4.508282e-01,-6.930544e-01,-5.082478e-01,-5.156417e-01,-8.333189e-01,-6.898818e-01,-6.163222e-01,...,-5.689778e-01,-5.948407e-01,-4.263973e-01,-2.630127e-01,-6.103545e-01,-9.036469e-01,-1.038085e+00,-6.815585e-01,-6.917205e-01,0.000000
50%,-5.600022e-03,-7.390739e-01,-9.637722e-02,-4.508282e-01,7.365524e-02,-3.876146e-01,-3.555344e-01,-3.912476e-02,1.666886e-01,-2.740277e-01,...,-4.187741e-01,-2.005985e-02,-4.263973e-01,-2.630127e-01,9.096853e-02,6.091188e-02,-1.593796e-01,1.255630e-02,-1.881173e-01,1.000000
75%,8.889722e-01,7.570271e-01,8.863953e-01,3.627535e-03,7.125800e-01,-6.746321e-03,1.247877e-01,7.090859e-01,1.023259e+00,3.019356e-01,...,-6.154617e-02,5.547210e-01,3.947028e-01,-2.630127e-01,7.508374e-01,8.647108e-01,8.950672e-01,6.791974e-01,4.650491e-01,1.000000
max,1.694087e+00,2.253128e+00,1.705372e+00,1.407601e+01,1.734860e+00,1.773906e+01,3.006720e+00,2.280839e+00,1.023259e+00,1.640933e+01,...,3.262898e+00,4.578187e+00,4.500203e+00,3.802098e+00,1.864086e+00,1.990029e+00,1.773773e+00,2.679170e+00,4.319532e+00,1.000000

## Save Scaler Model

In [12]:
import joblib
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']